stages:
  - orchestrate

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_COMMIT_TAG'

default:
  interruptible: true

variables:
  GIT_STRATEGY: fetch

.javascript_assignment03_changes: &javascript_assignment03_changes
  - courses/javascript/assignment-01-task-manager/**/*
  - courses/javascript/assignment-02-ts-task-manager/**/*
  - courses/javascript/assignment-03-ci-cd-1/**/*
  - .gitlab-ci.yml

.javascript_assignment04_changes: &javascript_assignment04_changes
  - courses/javascript/assignment-04-vue-secure-todo/**/*
  - .gitlab-ci.yml

.assignment18_changes: &assignment18_changes
  - courses/webapp-csharp/assignment-18-dental-clinic-platform/**/*
  - .gitlab-ci.yml

.assignment03_changes: &assignment03_changes
  - courses/webapp-csharp/assignment-03-multi-gym-management-system/**/*
  - .gitlab-ci.yml

javascript_assignment03_pipeline:
  stage: orchestrate
  trigger:
    include:
      - local: "courses/javascript/assignment-03-ci-cd-1/.gitlab-ci.yml"
    strategy: depend
  rules:
    - changes: *javascript_assignment03_changes
    - when: never

javascript_assignment04_pipeline:
  stage: orchestrate
  trigger:
    include:
      - local: "courses/javascript/assignment-04-vue-secure-todo/.gitlab-ci.yml"
    strategy: depend
  rules:
    - changes: *javascript_assignment04_changes
    - when: never

assignment18_pipeline:
  stage: orchestrate
  trigger:
    include:
      - local: "courses/webapp-csharp/assignment-18-dental-clinic-platform/.gitlab-ci.yml"
    strategy: depend
  rules:
    - changes: *assignment18_changes
    - when: never

assignment03_pipeline:
  stage: orchestrate
  trigger:
    include:
      - local: "courses/webapp-csharp/assignment-03-multi-gym-management-system/.gitlab-ci.yml"
    strategy: depend
  rules:
    - changes: *assignment03_changes
    - when: never
