stages:
  - build
  - test
  - package
  - deploy

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_COMMIT_TAG'

default:
  interruptible: true

variables:
  GIT_STRATEGY: fetch
  ASSIGNMENT_18_PATH: courses/webapp-csharp/assignment-18-dental-clinic-platform

include:
  - local: "courses/webapp-csharp/assignment-18-dental-clinic-platform/.gitlab-ci.yml"
