/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSessionsRouteImport } from './routes/_auth.sessions'
import { Route as AuthProfileRouteImport } from './routes/_auth.profile'
import { Route as AuthMembershipsRouteImport } from './routes/_auth.memberships'
import { Route as AuthAdminRouteImport } from './routes/_auth.admin'
import { Route as AuthSessionsSessionIdRouteImport } from './routes/_auth.sessions.$sessionId'
import { Route as AuthAdminSessionsRouteImport } from './routes/_auth.admin.sessions'
import { Route as AuthAdminMembersRouteImport } from './routes/_auth.admin.members'
import { Route as AuthAdminCategoriesRouteImport } from './routes/_auth.admin.categories'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSessionsRoute = AuthSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMembershipsRoute = AuthMembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSessionsSessionIdRoute = AuthSessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => AuthSessionsRoute,
} as any)
const AuthAdminSessionsRoute = AuthAdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminMembersRoute = AuthAdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminCategoriesRoute = AuthAdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/memberships': typeof AuthMembershipsRoute
  '/profile': typeof AuthProfileRoute
  '/sessions': typeof AuthSessionsRouteWithChildren
  '/admin/categories': typeof AuthAdminCategoriesRoute
  '/admin/members': typeof AuthAdminMembersRoute
  '/admin/sessions': typeof AuthAdminSessionsRoute
  '/sessions/$sessionId': typeof AuthSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/memberships': typeof AuthMembershipsRoute
  '/profile': typeof AuthProfileRoute
  '/sessions': typeof AuthSessionsRouteWithChildren
  '/admin/categories': typeof AuthAdminCategoriesRoute
  '/admin/members': typeof AuthAdminMembersRoute
  '/admin/sessions': typeof AuthAdminSessionsRoute
  '/sessions/$sessionId': typeof AuthSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/admin': typeof AuthAdminRouteWithChildren
  '/_auth/memberships': typeof AuthMembershipsRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/sessions': typeof AuthSessionsRouteWithChildren
  '/_auth/admin/categories': typeof AuthAdminCategoriesRoute
  '/_auth/admin/members': typeof AuthAdminMembersRoute
  '/_auth/admin/sessions': typeof AuthAdminSessionsRoute
  '/_auth/sessions/$sessionId': typeof AuthSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/memberships'
    | '/profile'
    | '/sessions'
    | '/admin/categories'
    | '/admin/members'
    | '/admin/sessions'
    | '/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/memberships'
    | '/profile'
    | '/sessions'
    | '/admin/categories'
    | '/admin/members'
    | '/admin/sessions'
    | '/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/admin'
    | '/_auth/memberships'
    | '/_auth/profile'
    | '/_auth/sessions'
    | '/_auth/admin/categories'
    | '/_auth/admin/members'
    | '/_auth/admin/sessions'
    | '/_auth/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sessions': {
      id: '/_auth/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthSessionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/memberships': {
      id: '/_auth/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof AuthMembershipsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sessions/$sessionId': {
      id: '/_auth/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthSessionsSessionIdRouteImport
      parentRoute: typeof AuthSessionsRoute
    }
    '/_auth/admin/sessions': {
      id: '/_auth/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AuthAdminSessionsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/members': {
      id: '/_auth/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthAdminMembersRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/categories': {
      id: '/_auth/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthAdminCategoriesRouteImport
      parentRoute: typeof AuthAdminRoute
    }
  }
}

interface AuthAdminRouteChildren {
  AuthAdminCategoriesRoute: typeof AuthAdminCategoriesRoute
  AuthAdminMembersRoute: typeof AuthAdminMembersRoute
  AuthAdminSessionsRoute: typeof AuthAdminSessionsRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminCategoriesRoute: AuthAdminCategoriesRoute,
  AuthAdminMembersRoute: AuthAdminMembersRoute,
  AuthAdminSessionsRoute: AuthAdminSessionsRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthSessionsRouteChildren {
  AuthSessionsSessionIdRoute: typeof AuthSessionsSessionIdRoute
}

const AuthSessionsRouteChildren: AuthSessionsRouteChildren = {
  AuthSessionsSessionIdRoute: AuthSessionsSessionIdRoute,
}

const AuthSessionsRouteWithChildren = AuthSessionsRoute._addFileChildren(
  AuthSessionsRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthMembershipsRoute: typeof AuthMembershipsRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthSessionsRoute: typeof AuthSessionsRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthMembershipsRoute: AuthMembershipsRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthSessionsRoute: AuthSessionsRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
